### ISSUE TITLE
Setting value to empty string

### ISSUE THREAD

**Issue by kenjones-cisco** [mikefarah/yaml#11]
Version: 1.10

File: (project.yml)
```yaml
metadata:
  name: example
  version: 0.4.0
  pretag: dev
```
Command:
```bash
    yaml write -i project.yml metadata.pretag ''
```

Response:
```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x5e3500, 0xc4200100c0)
        /usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
main.parseValue(0x7ffd1417ced1, 0x0, 0x1, 0xc4200ae880)
        /Users/mikefarah/dev/go/src/github.com/mikefarah/yaml/yaml.go:199 +0x83e
main.updateYaml(0xc4200bc2d0, 0x3, 0x5, 0x0, 0xc4200e3c77)
        /Users/mikefarah/dev/go/src/github.com/mikefarah/yaml/yaml.go:188 +0x2e1
main.writeProperty(0xc4201481e0, 0xc4200bc2d0, 0x3, 0x5)
        /Users/mikefarah/dev/go/src/github.com/mikefarah/yaml/yaml.go:162 +0x58
github.com/mikefarah/yaml/Godeps/_workspace/src/github.com/spf13/cobra.(*Command).execute(0xc4201481e0, 0xc4200bc280, 0x5, 0x5, 0xc4201481e0, 0xc4200bc280)
        /Users/mikefarah/dev/go/src/github.com/mikefarah/yaml/Godeps/_workspace/src/github.com/spf13/cobra/command.go:547 +0x411
github.com/mikefarah/yaml/Godeps/_workspace/src/github.com/spf13/cobra.(*Command).Execute(0xc4201485a0, 0xc4200e3f10, 0x3)
        /Users/mikefarah/dev/go/src/github.com/mikefarah/yaml/Godeps/_workspace/src/github.com/spf13/cobra/command.go:630 +0x398
main.main()
        /Users/mikefarah/dev/go/src/github.com/mikefarah/yaml/yaml.go:41 +0x449
```

Seems like setting a value to empty should be valid, but instead it will panic.

**Comment by kenjones-cisco** [comment]
After reading through the code:
```go
func parseValue(argument string) interface{} {
	var value, err interface{}
	var inQuotes = argument[0] == '"'
	if !inQuotes {
		value, err = strconv.ParseFloat(argument, 64)
		if err == nil {
			return value
		}
		value, err = strconv.ParseBool(argument)
		if err == nil {
			return value
		}
		return argument
	}
	return argument[1 : len(argument)-1]
}
```

The unquoted empty string was passed in, as a result that is not understood. By explicitly passing in the quoted empty string, the result seems to work.

The workaround seems to be doing the following:
```bash
    yaml write -i project.yml metadata.pretag '""'
```

The result then look like this:
```yaml
metadata:
  name: example
  version: 0.4.0
  pretag: ""
```

The desired state would result in the following:
```yaml
metadata:
  name: example
  version: 0.4.0
  pretag:
```

**Comment by mikefarah** [comment]
Ah ok cool :)

I've got a fix I should have out soon, need to check the len of arguments in the 'inQuotes' declaration

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yaml/releases/tag/1.11
